name: graphql_codegen
description: "Simple, opinionated, codegen library for GraphQL"
version: 0.0.1-alpha.1
homepage: https://github.com/heftapp/graphql_codegen
repository: https://github.com/heftapp/graphql_codegen

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  http: ^0.13.3
  gql: ^0.13.0-nullsafety.2
  build: ^2.0.1
  glob: ^2.0.1
  code_builder: ^4.0.0
  dart_style: ^2.0.1
  built_collection: ^5.0.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.17.4
  build_test: ^2.1.0
  build_runner: ^2.0.3
  json_serializable: ^4.1.2
  json_annotation: ^4.0.1
