name: graphql_codegen_example

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.1
  graphql_flutter: 5.0.1-beta.5
  flutter:
    sdk: flutter


dev_dependencies:
  json_serializable: ^4.1.2
  graphql_codegen: 
    path: "../"
  build_runner: ^2.0.3
  analyzer: ^1.7.0
  test: ^1.17.4
