name: graphql_codegen_example

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  graphql_flutter: 5.1.0
  graphql: 5.1.1
  flutter:
    sdk: flutter


dev_dependencies:
  graphql_codegen: 
    path: "../"
  build_runner: ^2.0.3
  test: ^1.17.4
