name: graphql_codegen
description: |
  Simple, opinionated, codegen library for GraphQL. It allows you to
  generate serializers and client helpers to easily call and parse your data.

version: 1.2.3
homepage: https://github.com/heftapp/graphql_codegen/tree/main/packages/graphql_codegen
repository: https://github.com/heftapp/graphql_codegen/tree/main/packages/graphql_codegen

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  gql: ^1.0.0
  build: ^2.0.1
  glob: ^2.0.1
  code_builder: ^4.2.0
  dart_style: ^3.0.0
  built_collection: ^5.0.0
  path: ^1.8.0
  gql_code_builder: ^0.13.1
  recase: ^4.0.0
  json_annotation: ^4.9.0
dev_dependencies:
  test: ^1.17.4
  build_test: ^2.1.0
  build_runner: ^2.0.3
  json_serializable: ^6.9.5
  graphql: ^5.2.0-beta.3
  lints: ^5.1.1
