name: graphql_codegen_config
description: "Config library for graphql_codegen"
version: 0.2.0
homepage: https://github.com/heftapp/graphql_codegen/tree/main/graphql_codegen_config
repository: https://github.com/heftapp/graphql_codegen/tree/main/graphql_codegen_config

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  json_annotation: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^4.1.4
  test: ^1.18.1
