
name: graphql_switch

description: | 
  If you like Relay, you're gonna love GraphQL Switch!

version: 0.0.1-alpha.1
homepage: https://github.com/heftapp/graphql_codegen/tree/main/packages/graphql_switch
repository: https://github.com/heftapp/graphql_codegen/tree/main/packages/graphql_switch

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  analyzer: '>=4.0.0 <6.0.0'
  gql: ^0.14.0
  equatable: ^2.0.0
  build: ^2.0.1
  glob: ^2.0.1
  code_builder: ^4.2.0
  dart_style: ^2.0.1
  built_collection: ^5.0.0
  path: ^1.8.0
  gql_code_builder: ^0.7.1
  recase: ^4.0.0
  json_annotation: ^4.7.0
  graphql_codegen: "^0.11.0-beta.1"
  graphql: "^5.1.2-beta.2"
  flutter_hooks: ^0.18.0

dev_dependencies:
  test: ^1.17.4
  build_test: ^2.1.0
  build_runner: ^2.0.3
  json_serializable: ^6.1.5
  lints: ^2.0.0
